import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(' Addition:-',a + b)
print('Subtraction:-',a - b)
print('Subtraction:-',a * b)
print('Division:-',a / b)
print('Modulus:-',a % b)
print('Cude:-',a ** 2)
print('Floor Division:-',a // b)
